---
type: l2leaf

l2leaf:
  defaults:
    platform: cEOS
    spanning_tree_mode: mstp
    uplink_switches: [ leaf-3a, leaf-3b ]
    uplink_interfaces: [ Ethernet49, Ethernet50 ]
  node_groups:
    - group: IDF3_3C
      filter:
        tags: [ "IDF3_DATA", "IDF3_VOICE" ]
      campus_access_pod: IDF3
      cv_tags_topology_type: member-leaf
      mlag: false
      nodes:
        - name: member-leaf-3c
          id: 6
          mgmt_ip: 192.168.0.19/24
          uplink_switch_interfaces: [ Ethernet51, Ethernet51 ]
    - group: IDF3_3D
      filter:
        tags: [ "IDF3_DATA", "IDF3_VOICE" ]
      campus_access_pod: IDF3
      cv_tags_topology_type: member-leaf
      mlag: false
      nodes:
        - name: member-leaf-3d
          id: 7
          mgmt_ip: 192.168.0.20/24
          uplink_switch_interfaces: [ Ethernet52, Ethernet52 ]
    - group: IDF3_3E
      filter:
        tags: [ "IDF3_DATA", "IDF3_VOICE" ]
      campus_access_pod: IDF3
      cv_tags_topology_type: member-leaf
      mlag: false
      nodes:
        - name: member-leaf-3e
          id: 8
          mgmt_ip: 192.168.0.21/24
          uplink_switch_interfaces: [ Ethernet53/1, Ethernet53/1 ]
