---
- name: Build Switch configuration
  hosts: cvp
  gather_facts: false

  tasks:

    - name: Generate Intended Config and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'SITE1_FABRIC'
        configlets_prefix: 'AVD'
        state: present
