! Command: show running-config
! device: s2-leaf2 (cEOSLab, EOS-4.32.2F-38195967.4322F (engineering build))
!
no aaa root
!
username arista privilege 15 role network-admin secret sha512 $6$arista$lBvriN87OUXt1osF9iGpxa1bXc7/xGYX5ExRbMiXtvZ5q01ajAaTo5XmQMn2kWT4BqBSZiDU3ogiN2hMkUM0X0
username arista ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdlaFZiP2W3I0Mo4tN48idWeOYUIpV53jViA1KGGulNcAYFQqJ5CzRN5pi8jttVITmiAHBxP8AF6CYebS7DWS6KQNlLIoWD0hbE60ATuWCYZDiGHTV1MBIxgIy17hLrzI0ZRcupqxgjM9Y9qaZHsp9OYQxLec3j3Fa8lkugT/zdyW0Hx/CT+mAgyS3UIzBCZMNMZgmDtXZLCWHSm7cvj8ZNksTgr+9pgQizQFxIHRhWGNsc6RF4PVv7qWLLVDC0EXS+wNRR/gQ+FZYOMHMk+1qVWr17bPT6WBtnWRQdItWLnXT+LiH52Uea2YXSML78Y1260LgoA6VLh4Y4b8imX2V arista@ps-avd-14-32d5cd42-eos
!
management api http-commands
   no shutdown
   !
   vrf default
      no shutdown
!
daemon TerminAttr
   exec /usr/bin/TerminAttr -cvaddr=192.168.0.5:9910 -cvauth=token,/tmp/token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs
   no shutdown
!
vlan internal order ascending range 1006 1199
!
no service interface inactive port-id allocation disabled
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname s2-leaf2
dns domain atd.lab
!
spanning-tree mode mstp
no spanning-tree vlan-id 4094
spanning-tree mst 0 priority 16384
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vlan 30
   name Thirty
!
vlan 4094
   name MLAG_PEER
   trunk group MLAG
!
aaa authorization exec default local
!
interface Port-Channel1
   description MLAG_PEER_s2-leaf1_Po1
   switchport mode trunk
   switchport trunk group MLAG
!
interface Port-Channel2
   description SPINES_Po2
   switchport trunk allowed vlan 30
   switchport mode trunk
   mlag 2
!
interface Port-Channel4
   description s2-host1
   switchport access vlan 30
   mlag 4
   spanning-tree portfast
!
interface Ethernet1
   description MLAG_PEER_s2-leaf1_Ethernet1
   channel-group 1 mode active
!
interface Ethernet2
   description S2-SPINE1_Ethernet3
   channel-group 2 mode active
!
interface Ethernet3
   description S2-SPINE2_Ethernet3
   channel-group 2 mode active
!
interface Ethernet4
   description s2-host1_eth2
   channel-group 4 mode active
!
interface Ethernet6
   description MLAG_PEER_s2-leaf1_Ethernet6
   channel-group 1 mode active
!
interface Management0
   description oob_management
   ip address 192.168.0.23/24
!
interface Vlan4094
   description MLAG_PEER
   mtu 1500
   no autostate
   ip address 10.2.253.1/31
!
no ip routing
!
mlag configuration
   domain-id RACK1
   local-interface Vlan4094
   peer-address 10.2.253.0
   peer-link Port-Channel1
   reload-delay mlag 300
   reload-delay non-mlag 330
!
ip route 0.0.0.0/0 192.168.0.1
!
ntp server 192.168.0.1 iburst local-interface Management0
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
end