---
# Credentials for CVP and EOS Switches
ansible_user: arista
ansible_password: "{{ lookup('env', 'LABPASSPHRASE') }}"
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

# arista.avd.cv_deploy role parameters
cv_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc0NTk4NTk2MjA0NjMzNzg2NjYsImRzbiI6InRvbnkiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxNzQ5ODI3MTA5LCJpYXQiOjE3NDk3NDA1MzMsIm9naSI6Mywib2duIjoiRGVmYXVsdCIsInNpZCI6Ijk3MThmYTUxNWUxYzZkZmM5OTIzNTI3NDZhOWJlYzEzYjQwZTBmNWNkNWZhZjcwZWVmOTA5N2QzOWRlYTRhN2MtOTFkcHhic0xiSzRzMXVVQ19tLUJYTGNmNThLWmRiRFRCZEI2VUlMbCJ9.TfA4sU7qaLJqfs1slAw1wMOI2F-LILzUacm32M8wZZ3fmdOptnkvyCRUusHJ0bhWwF9dJRZREfKuL1Gfij3EGExq9eeokFiYL1H_9gGU2BXk2Jap1kMxLAtY4MPqngi0Y-hPlDUcoJbYWG9I6dKahaDN4EXleuE-0vHaXSflW1MGMFnn-1UE7xzo12_3wLP4_81-HqGu5VBft4lwP6Bj8nrLVFkmgJ8zRN53aZSdhngeEw2TuEPXAW0RjEoZh1jYLNpo3KdvNIGopGY2ywZXg987dzr1D-swKFsW4iDPUUK8Wl9-KZwyjS8zb_irDAnkW0iqLCxGvMOL0FLrSazAgrPScwJzQ6fciqDXqBYWaedUa_HHrclYgF8uyhtJ0xon0Q6EWMDNV4kwhYy4pZdED6D6B5ssJdFqDnlgjqWfgKVsqu6ha9_UzIhrLHx2h72ekqF8e-ete-g42vaGBC3cFdgy9FLbBErK_MREPsjRsyI92Y3EmYu_5NINXj768WmBzalAGU2E9S8iG8jdTmnLnUjQ9nE3zJqTBKWfpLqw0PyRk8LJpb7q-X4sEcVNJ09kR4t0Zf2x3HX6mi6gGwigIGJ4OzVG2ZXiaEGL0_ysQVVxdveiC-FSU1SOnxGN5_pQT0KcopZlpmCRsv03G8k9ap0gMDM7Nz3lyNczt48mHhA"
cv_server: cvp
cv_verify_certs: false

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
    ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"

# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: 192.168.0.1
      iburst: true
      local_interface: Management0

# Domain/DNS
dns_domain: atd.lab

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.0.5:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: token
    token_file: "/tmp/token"
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# CVP node variables
cv_collection: v3
execute_tasks: true
