---
# Credentials for CVP and EOS Switches
ansible_user: arista
ansible_password: "{{ lookup('env', 'LABPASSPHRASE') }}"
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

# arista.avd.cv_deploy role parameters
cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc0NTk4NTk2MjA0NjMzNzg2NjcsImRzbiI6IlNlcnZpY2VBY2NvdW50MSIsImRzdCI6ImFjY291bnQiLCJleHAiOjE4MjE4MzczNzYsImlhdCI6MTc1ODE2MDU5Mywib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiYzMyMjBjNWViOGM4NjcyN2EwOWU4ZGU1YmI1YTRjNzQ0YzJiYTAyNDU3Y2NlYWM0ZDQ4YzI0MGRiNDNiNTkzNi10cGROQWc2VjNWMExNMWJNTVFET0lrWGFWTV9jbWNXU2p0aEtjYklCIn0.yUIc_5z0Ay0PP1JfLd4MHUnNaD0MJ-mmtu_e8TubsaTSS6mpdwSCBzHd7GHRfv3wrYUEnbirj26S_ADWq1obHHDYv1HMxPabNU48ck_uboxjYXME4jc8vFdASx5f5OB_UNI51rNHMD8JCwiQPLAXiNbZ5WFVcinBaJXBXxxJPGvDSr_85u22DQIGfnp--X8jPUURfutRfnLGGSLcxSFIpigHMgM9kx7MYvvXPjX9NAvr06abu4eh1AAsrLq_X1H5UpFRkDECZzMG0I9oPEbgub2mS0_0sNKNdqAEWs81vxMAjDYlWcn27TeORfqq6s-BL3Op2cm5kNic6pcBNIM1UouO8a59gyhg-fG1rY0yR-eUIa-Gx2szxOGKYggGTXE8IeqqtXMfb1CLCWTZrVYJHoanz691TUhWzO-1Z2Fp7Yc6Hsbp7-lu_kYOHmLiNkQugXYNphxNp05VhhRc4KkiE7Lpa0Bu1fLCHayslfDr_N6yHMmk0JJ1iALa2E7Hb0xvb_RDAYpeON1Oo1tCz-MfIHi99KNAnrd5y2IoNAak884l7v4soOIFIj9woO0YzaMVqVtu-umYO-5Qy7JUTj_y5QHIbuU0kjT-QIHkCcvszQVDX7D7UfjUxFjm2hSn5msSIVyeg4jx0P3b2fRfz19HdW0JYLIJmFUNoEw0TYmXs-4
cv_server: cvp
cv_verify_certs: false

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
    ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"

# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: 192.168.0.1
      iburst: true
      local_interface: Management0

# Domain/DNS
dns_domain: atd.lab

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.0.5:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: token
    token_file: "/tmp/token"
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# CVP node variables
cv_collection: v3
execute_tasks: true
