---
# Credentials for CVP and EOS Switches
ansible_user: arista
ansible_password: "{{ lookup('env', 'LABPASSPHRASE') }}"
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

# arista.avd.cv_deploy role parameters
cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc0NTk4NTk2MjA0NjMzNzg2NjgsImRzbiI6ImxhYiIsImRzdCI6ImFjY291bnQiLCJleHAiOjIwNDY5OTYxMDEsImlhdCI6MTc1ODE2MDkwNiwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiNGM4MGE1NDJkN2ZjY2Y1YjhmY2ZkYmUxNjFkOWM0OWU5YTEwODIzMjk2YTllYTBkYTA1YWQ3NWQ0OTRiNDliMS1QYTlUdHlpMVRmYUpqTXdCdWhqSWlfbHdHTmE3RzF3N2o1SklwRU9sIn0.KTHf4VJml27g5J6FtV6iYtkU-Ld3C2pqz8mZYiACnKQ1bxnbw2d2y_oLRNrvS8fyWhPLW81jp2PzMSwornMizB0ZDTjcILIvro3wR4yrp1YkgA8pvbvsxXtKW7dVuynHbT1jkxLO2gIbI58rZN14BGU_OMdxtvCFJYJYtMM5kTKnDBIEPl5MjMMI6NEP4XZgXdmaNlGSKLAYpD-HEUESteYyKfhEcC116sV7f0idSqbN3lNcM4kkyFVKBpI8IrxiqgZg5jxCWiA7rtBwHpRSkZxN6vVJUhcOy03cC_baENrv3Bo0ul0F_6ZvW00C1ARDqZ9mDdyp_hq-QjhGgf1c1QDDnbaC_NhmobxiQ4Zu3rwkKJbU1RSaIOkzXMADNh4FBe9DaiCpljfbt2F3JDTQu5RAYbL0g4B72HN4PP16JtHTRfGaFku7hq3c_5ayrFeer1sOXmW9x-4M3oBdIG7H24Op_zGz6CHKxPn2qEz-CAI1iSA7uBIjXo0k1ZL_68Kr876WP4Gj3x8SqhmxK6UjR63MRuOXM-wRG1Q0c9evpwvEAhpLN-0ju2s4mzPPm99twzX0uayWltW016guV2Y4tIpFHqJ2I04bcUqR_je7GnzTdA7OqmvFw4ij2nwOcPKJpVfoT3OGW-awVYO2m0ge50xXycw55ibpg-6kLsFJd9M
cv_server: cvp
cv_verify_certs: false

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
    ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"

# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: 192.168.0.1
      iburst: true
      local_interface: Management0

# Domain/DNS
dns_domain: atd.lab

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.0.5:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: token
    token_file: "/tmp/token"
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# CVP node variables
cv_collection: v3
execute_tasks: true

# Login Banner
banners:
  motd: |
    You shall not pass. Unless you are authorized. Then you shall pass.
    EOF

# Syslog
logging:
  vrfs:
    - name: default
      source_interface: Management0
      hosts:
        - name: 10.200.0.108
        - name: 10.200.1.108
