---
- name: validate states on EOS devices using ANTA
  hosts: "{{ target_hosts }}"
  gather_facts: false
  tasks:
    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        # To enable ANTA this is no longer needed as it's not the default behavior since AVD 5.0.0
        # use_anta: true
        # To save catalogs
        save_catalog: true
        skip_tests:
          - category: AvdTestNTP
            tests: 
              - VerifyNTP
          - category: AvdTestHardware
            tests:
              - VerifyEnvironmentPower
              - VerifyTemperature
              - VerifyEnvironmentCooling
              - VerifyTransceiversManufacturers
